name: .NET Core CI

on: [push]

env:
  AZURE_WEBAPP_NAME: developmentworkshop
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  DOTNET_VERSION: '5.0.x'
  AZURE_FUNCTION_NAME: wrkshpfunc
  AZURE_FUNCTION_PACKAGE_PATH: '.'
  DOTNET_VERSION_FUNCTION: '3.1.x'

jobs:
  frontend:
    environment: DevWorkshop
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - uses: actions/checkout@main
      
      # Setup .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }} 
      
      # Run dotnet build and publish
      - name: dotnet build and publish
        working-directory: ./Frontend
        run: |
          dotnet restore
          dotnet build --configuration Release
          dotnet publish -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/Frontend/myapp' 
          
      # Deploy to Azure Web apps
      - name: 'Run Azure webapp deploy action using publish profile credentials'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
          publish-profile: ${{ secrets.PUBLISH_PROFILE  }} # Define secret variable in repository settings as per action documentation
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/Frontend/myapp'
  
  function:
    environment: DevWorkshop
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - uses: actions/checkout@main
      
      # Setup .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION_FUNCTION }} 
      
      # Run dotnet build and publish Function
      - name: dotnet build and publish Function
        working-directory: ./Function
        run: |
          dotnet restore
          dotnet build --configuration Release
          dotnet publish -c Release -o '${{ env.AZURE_FUNCTION_PACKAGE_PATH }}/myfunc' 
          
      # Deploy to Azure Functions
      - name: 'Run Azure Function deploy action using publish profile credentials'
        uses: azure/functions-action@v1
        with: 
          app-name: ${{ env.AZURE_FUNCTION_NAME }} # Replace with your app name
          publish-profile: ${{ secrets.PUBLISH_PROFILE_FUNCTION  }} # Define secret variable in repository settings as per action documentation
          package: '${{ env.AZURE_FUNCTION_PACKAGE_PATH }}/Function/myfunc'
